import type { FacultyData } from '../csds/FacultyProfileView';

const faculty: FacultyData = {
  name: "Dr. Tatwadarshi Nagarhalli",
  designation: "Associate Professor & Head of Department",
  department: "Artificial Intelligence and Data Science",
  dateOfJoining: "15 February 2021",
  email: "tatwadarshi.nagarhalli@vcet.edu.in",
  experienceYears: "12",
  papersPublished: "55",
  photo: "faculty/aids/tatwadarshi-nagarhalli.jpg",
  qualifications: [
    "Ph.D. (Computer Engineering)",
    "Ph.D. (Sanskrit)",
    "M.E. (Computer Engineering)",
    "M.A. (Sanskrit)",
    "PGDBA (E-Business)",
  ],
  specialization: [
    "Machine Learning",
    "Natural Language Processing",
    "Artificial Intelligence",
    "Data Science",
    "Data Security",
  ],
  roles: [
    { icon: "fa-crown", label: "Head of Department (HOD)" },
  ],
  books: [
    { title: "Cyber Security Threats and Challenges Facing Human Life", subtitle: "Edited Book ┬À Chapman & Hall CRC Press, Taylor & Francis Group, UK ┬À ISBN: 9781032111285 ┬À e-ISBN: 9781003218555" },
    { title: "Intelligent Approaches to Cyber Security", subtitle: "Edited Book ┬À Chapman & Hall CRC Press, Taylor & Francis Group, UK ┬À ISBN: 9781032521619 (Scopus Indexed)" },
    { title: "Natural Language Processing ÔÇô Sem VII, B.E. Computer Engineering, University of Mumbai", subtitle: "Authored Book ┬À ISBN: 9789355830913" },
    { title: "Natural Language Processing ÔÇô Sem VIII, B.E. Electronics & Telecommunication / Electronics & CS, University of Mumbai", subtitle: "Authored Book ┬À ISBN: 9789389926798" },
    { title: "Natural Language Processing ÔÇô Sem VIII, B.E. Computer Engineering, Savitribai Phule Pune University", subtitle: "Authored Book ┬À ISBN: 9789389926781" },
    { title: "Cyber Security ÔÇô Sem VII, B.E. Artificial Intelligence and Data Science, SPPU", subtitle: "Authored Book" },
    { title: "Introduction and Importance of ML Techniques in Cyber Security", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "Evaluation of Learning Techniques in Intrusion Detection System", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "Analysis of RNN and CNN Techniques in Blood Cell Classification", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "Evaluating the Effectiveness of CNN in Detecting Brain Tumour", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "Fundamental Models in Machine Learning and Deep Learning", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "A Deep Learning-based Approach for Fruit Gradation in the Post-Harvesting Phase", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "Significance of Intelligent Learning Techniques in IoT Applications", subtitle: "Book Chapter ┬À CRC Press" },
    { title: "A Review of Security Challenges and Solutions for Healthcare IoT-based Systems", subtitle: "Book Chapter ┬À CRC Press" },
  ],
  isbnNumbers: [
    "9781032111285",
    "9781003218555",
    "9781032521619",
    "9789355830913",
    "9789389926798",
    "9789389926781",
  ],
  patents: [
    { title: "Patent 1 ÔÇô Deep Learning / NLP / Data Security domain (details to be updated)" },
    { title: "Patent 2 ÔÇô Deep Learning / NLP / Data Security domain (details to be updated)" },
    { title: "Copyright 1 (of 9 registered)" },
    { title: "Copyright 2" },
    { title: "Copyright 3" },
    { title: "Copyright 4" },
    { title: "Copyright 5" },
    { title: "Copyright 6" },
    { title: "Copyright 7" },
    { title: "Copyright 8" },
    { title: "Copyright 9" },
  ],
  awards: [
    {
      icon: "fa-award",
      title: "Best Paper Award",
      subtitle: "2nd IEEE International Conference on Engineering and Technology (ICETECH) ┬À 17ÔÇô18 March 2016 ┬À Coimbatore, India ┬À Paper: \"A New Approach to Hindi Text Steganography using Modified Vedic Numeric Code\"",
    },
  ],
  memberships: [
    { label: "IEEE" },
    { label: "ISTE" },
    { label: "NSDC" },
  ],
  websites: [
    { href: "https://www.linkedin.com/in/tatwadarshipn/",                                        icon: "fa-linkedin",      name: "LinkedIn",        sub: "linkedin.com/in/tatwadarshipn" },
    { href: "https://www.scopus.com/authid/detail.uri?authorId=57202110143",                     icon: "fa-search",        name: "Scopus Profile",  sub: "Author ID: 57202110143" },
    { href: "https://scholar.google.com/citations?user=SAVvoPgAAAAJ&hl=en",                      icon: "fa-user-graduate", name: "Google Scholar",  sub: "Citation Profile" },
    { href: "https://orcid.org/0000-0002-8282-6273",                                             icon: "fa-orcid",         name: "ORCID",           sub: "0000-0002-8282-6273" },
  ],
  eResources: [
    { title: "Security Threats to Machine Learning Systems",                   icon: "fa-shield-alt",  url: "https://www.analyticsvidhya.com/" },
    { title: "Role of Machine Learning in Natural Language Processing",        icon: "fa-language",    url: "https://www.analyticsvidhya.com/" },
  ],
};

export default faculty;
